Map<String, String> englishText = {

  //Home Screen
  'etender' : 'E-Tender',
  'els' : 'E-Auction (Leasing & Sale)',
  'customsearch':'Custom\nSearch',
  'closingtoday':'Closing\nToday',
  'tenderstatus':'Tender\nStatus',
  'highvaluetender':'High Value\nTender',
  'rlu':'RA-Live&\nUpcoming',
  'raclosed': 'RA\nClosed',
  'searchpo': 'Search\nPO',
  'generateotp': 'Generate\nOTP',
  'parcelpymt':'Parcel\nPayment',
  'liveauc': 'Live\nAuction',
  'upcomingauction' : 'Upcoming\nAuction',
  'publishedauc':'Published\nAuction',
  'secheduleauc':'Schedule\nAuction',
  'lotsearch':'Lot\nSearch',
  'esalecon':'E-Sale\nCondition',
  'aucunits': 'Auctioning\nUnits',
  'udmtitle': 'UDM',
  'crismmistitle': 'CRIS MMIS',
  'home': 'Home',
  'login': 'Login',
  'helpdesk': 'Helpdesk',
  'links': 'Links',
  'ireps' : 'IREPS',
  'welcome' : 'Welcome',
  'aboutus' : 'About Us',
  'rateus' : 'Rate Us',
  'exit' : 'Exit',
  'dbc' : 'Developed by CRIS',
  'exitapp' : 'Exit Application',
  'exitcnf' : 'Are you sure you want to leave?',
  'nostay' : 'No, stay',
  'yesexit' : 'Yes, exit',
  'version' : 'Version'
};