Map<String, String> hindiText = {

  //Home Screen
  'etender' : 'E-टेंडर (ई-निविदा) सेक्शन',
  'els' : 'E-ऑक्शन (लीजिंग और बिक्री) सेक्शन',
  'customsearch':'विशेष\nखोज',
  'closingtoday':'आज समाप्त\nहोने वाले',
  'tenderstatus':'निविदा\nस्थिति',
  'highvaluetender':'उच्च मूल्य\nनिविदा',
  'rlu':'आरए-लाइव और\nआगामी',
  'raclosed': 'आरए\nसमाप्त',
  'searchpo': 'क्रय आदेश\nखोज',
  'generateotp': 'ओटीपी जनरेट करें',
  'parcelpymt':'पार्सल\nभुगतान',
  'liveauc': 'लाइव\nनीलामी',
  'upcomingauction' : 'आगामी\nनीलामी',
  'publishedauc':'प्रकाशित\nनीलामी',
  'secheduleauc':'नीलामी\nअनुसूची',
  'lotsearch':'लॉट\nखोजें ',
  'esalecon':'ई-बिक्री\nशर्तें',
  'aucunits': 'नीलामी\nइकाइयाँ',
  'udmtitle': 'यूडीएम',
  'crismmistitle': 'क्रिस एम.एम.आई.एस',
  'home': 'होम',
  'login': 'लॉगिन',
  'helpdesk': 'सहायता केंद्र',
  'links': 'लिंक्स',
  'ireps' : 'आई.आर.ई.पी.एस',
  'welcome' : 'स्वागत',
  'aboutus' : 'हमारे बारे में',
  'rateus' : 'हमें रेटिंग दें',
  'logout' : 'लॉगआउट करें',
  'exit' : 'बाहर निकलना',
  'dbc' : 'CRIS द्वारा विकसित',
  'exitapp' : 'एप्लिकेशन से बाहर निकलें',
  'exitcnf' : 'क्या आपकी वाकई छोड़ने की इच्छा है?',
  'nostay' : 'नहीं, रहो',
  'yesexit' : 'हाँ, बाहर निकलें',
  'version' : 'संस्करण'
};